site_name: MCCoroutine
repo_url: https://github.com/Shynixn/MCCoroutine
site_author: Shynixn
nav:
  - 'Getting Started':
      - Introduction: README.md
      - Installation: gettingstarted.md
  - 'User Guide':
    - 'Suspending Plugin': newplugin.md
    - 'Suspending Listeners': listener.md
    - 'Suspending CommandExecutors': commandexecutors.md
    - 'Suspending Delayed, Repeating Tasks': repeatingtasks.md
    - 'Suspending Caches, Background Repeating Tasks': caching.md
    - 'Bridging non-suspendable functions to suspendable functions': bridge.md
  - 'Technical Guide':
    - Installation: listener.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.tabs.link
extra:
  generator: false
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
