name: MCCoroutine-Sample
version: 0.0.6
author: Shynixn
main: com.github.shynixn.mccoroutine.sample.MCCoroutineSamplePlugin
commands:
  mccor:
    description: Command for operations.
    useage: /<command>
    permission: mccoroutine.sample
    permission-message: You don't have permission.
